.\" make-sqldeveloper-package.1
.\"
.\" (2017-12-26)
.\"
.\" Copyright © 2009-2017 Lazarus Long <lazarus (dot) long (at) sapo (dot) pt>
.\"
.\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\"
.\"  This program is free software: you can redistribute it and/or modify  .\"
.\"  it under the terms of the GNU General Public License as published by  .\"
.\"  the Free Software Foundation, either version 3 of the License, or     .\"
.\"  (at your option) any later version.                                   .\"
.\"                                                                        .\"
.\"  This program is distributed in the hope that it will be useful,       .\"
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of        .\"
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         .\"
.\"  GNU General Public License for more details.                          .\"
.\"                                                                        .\"
.\"  You should have received a copy of the GNU General Public License     .\"
.\"  along with this program.  If not, see <http://www.gnu.org/licenses/>. .\"
.\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\".\"
.\"
.\" Debian package builder and installer for Oracle SQL Developer
.\"
.\"
.TH MAKE-SQLDEVELOPER-PACKAGE 1 2017-12-26 GNU "Oracle SQL Developer Debian package builder"
.\"
.SH NAME
make-sqldeveloper-package \- Oracle SQL Developer Debian package builder
.\"
.SH SYNOPSIS
.B make-sqldeveloper-package
.RI [options]\  <file>
.\"
.SH DESCRIPTION
\fBmake-sqldeveloper-package\fP is a utility that builds a Debian package for
\fIOracle SQL Developer\fP.
.PP
The \fIOracle SQL Developer\fP program is governed by the copyright holder
(\fIOracle USA, Inc.\fP), so you may be limited as to what you can do with the
resulting package (i.e. no redistribution, etc). This utility will simply help
you create the Debian package, it is your responsibility to use the resulting
package accordingly with the OTN license, a copy of which is included in the
created package, that you must agree on when downloading the source.
.PP
This utility will require you to download the "\fI\fBOracle SQL Developer\fP
for other platforms\fP" archive from <\fIhttp://www.oracle.com/technetwork/developer-tools/sql-developer/\fP>
to create the Debian package from.
.\"
.SH OPTIONS
.TP
\fB\-b\fP|\fB\--build-dir\fP \fI<dir>\fP
base directory to build package(s) (\fIautogenerated\fP)
.TP
\fB\-e\fP|\fB\--email\fP \fI<email>\fP
local maintainer email (\fIuse DEBEMAIL or auto-generate\fP)
.TP
\fB\-i\fP|\fB\--install\fP
install the generated package(s) - \fBneeds root privilege\fP (\fIno\fP)
.TP
\fB\-k\fP|\fB\--keep-dir\fP
keep the build directory (\fIno\fP)
.TP
\fB\-l\fP|\fB\--revision\fP \fI<number>\fP
local revision to append to package version (\fI1\fP)
.TP
\fB\-m\fP|\fB\--maintainer\fP \fI<name>\fP
local maintainer name (\fIuse DEBFULLNAME or leave empty\fP)
.TP
\fB\-q\fP|\fB\--quiet\fP
suppress normal output (\fIno\fP)
.TP
\fB\-r\fP|\fB\--root-command\fP \fI<command>\fP
command to gain root privilege for package build (\fIfakeroot\fP)
.TP
\fB\-s\fP|\fB\--skip-libraries\fP
skip building the shared libraries package(s) (\fIno\fP)
.TP
\fB\-u\fP|\fB\--upstream-version\fP \fI<version>\fP
force the upstream version (\fIautodetected\fP)
.TP
\fB\-x\fP|\fB\--extract-only\fP
prepare build tree, do not build package(s) [implies \fB-k\fP|\fB--keep-dir\fP] (\fIno\fP)
.TP
\fB\-h\fP|\fB\--help\fP
display the help screen
.TP
\fB\-v\fP|\fB\--version\fP
show the program version
.PP
.TP
\fB<file>\fP
the "\fIOracle SQL Developer for other platforms\fP" archive from
<\fIhttp://www.oracle.com/technetwork/developer-tools/sql-developer/\fP>
.\"
.SH AUTHOR
make-sqldeveloper-package was written by Lazarus Long <lazarus.long@sapo.pt>.
.PP
This manual page was written by Lazarus Long <lazarus.long@sapo.pt>,
for the Debian project (but may be used by others).
.\"
.\" EOF make-sqldeveloper-package.1
